name: Aggregate Helm Indexes
on:
  workflow_dispatch:
  repository_dispatch:
    types: [charts-updated]
concurrency:
  group: helm-index
jobs:
  aggregate:
    name: Aggregate Helm Indexes
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate Helm Indexes
        uses: markgoddard/helm-charts/.github/actions/aggregate-indexes@main
        with:
          repository: ${{ github.event.client_payload.repository }}
          changed_charts: ${{ github.event.client_payload.changed_charts }}
