name: Aggregate Helm Index
on:
  #schedule:
  #  - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
  repository_dispatch:
    types: [charts-updated]

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Download remote index files
        run: |
          mkdir -p temp-indexes
          
          # Download index from Cofide SPIRE Helm charts
          curl --fail -L -o temp-indexes/spiffe-helm-charts-hardened-index.yaml \
            https://markgoddard.github.io/spiffe-helm-charts-hardened/index.yaml
          
      - name: Merge remote indexes with local
        run: |
          pip install ruamel.yaml
          python3 .github/workflows/merge_indexes.py

      - name: Commit and push updated index
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
          git add index.yaml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update aggregated helm index for ${{ github.event.client_payload.repository }}\
          \
          Changed charts: ${{ github.event.client_payload.changed_charts }}"
            git push
          fi
